### ISSUE TITLE
Familiarize with Parsl

### ISSUE THREAD

**Issue by rushirajnenuji** [QGreenland-Net/parsl-exploration#1]

**Comment by trey-stafford** [comment]
[pdg_workflow.py](https://github.com/PermafrostDiscoveryGateway/viz-workflow/blob/develop/pdg_workflow/pdg_workflow.py): includes parsl config for the PDG on k8s

**Comment by trey-stafford** [comment]
Repo exploring the use of `parsl`: https://github.com/QGreenland-Net/parsl-exploration

Initial thoughts:

* Some elements don't feel "pythonic". E.g., "magic" kwargs on decorated functions (`stdout` and `stderr` on functions decorated wtih `@bash_app`)
* Limited documentation on how to use parsl on kubernetes
    * Workers require ability to connect to the machine running the parsl script, which means that machine must have a routable address. We work around this by sending the parsl script to kubernetes in a ConfigMap and running it with a Job. Is there a better way?
* Some error states result in 'orphaned' pods that go into a restart loop and need to be manually cleaned-up.

**Comment by mfisher87** [comment]
Are we familiar enough now?
